### ISSUE TITLE
ajuste no layout para retirar scroll horizontal

### ISSUE THREAD

**Issue by israelrodrigues01** [csamuelsm/secomp#1]
Olá! Me chamo Israel Rodrigues, aluno de Ciência da Computação pela UFCA e desenvolvedor Web. Entrei recente no site do SeComp e vizualizei um scroll horizontal no body. Gostaria de ajudá-lo, já solucionei e queria resolver no código para atualizar novamente aos usários.

**Comment by csamuelsm** [comment]
Já aceitei o pull request. Obrigado pela contribuição.
